name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-eslint:
    name: 'Lint: ESLint'
    uses: jrposada/github-actions/.github/workflows/npm-script.yml@v2
    with:
      script: 'lint:eslint'

  lint-format:
    name: 'Lint: Format'
    uses: jrposada/github-actions/.github/workflows/npm-script.yml@v2
    with:
      script: 'lint:format'

  lint-types:
    name: 'Lint: Types'
    uses: jrposada/github-actions/.github/workflows/npm-script.yml@v2
    with:
      script: 'lint:types'

  lint-commits:
    name: 'Lint: Commits'
    uses: jrposada/github-actions/.github/workflows/conventional-commits.yml@v2

  test-unit:
    name: 'Test: Unit'
    uses: jrposada/github-actions/.github/workflows/npm-script.yml@v2
    with:
      script: 'test:coverage'

  get-version:
    name: Get version
    permissions:
      contents: write
      pull-requests: write
    uses: jrposada/github-actions/.github/workflows/semantic-release.yml@v2
    with:
      dry-run: true

  build:
    name: 'Build'
    needs: ['get-version']
    uses: jrposada/github-actions/.github/workflows/tauri-build.yml@v2
    with:
      version: ${{ needs.get-version.outputs.version }}
      bundle-folder: ./src-tauri/target/release/bundle
      artifact-name: binary
      script: tauri build

  release:
    name: Release
    needs:
      [lint-eslint, lint-format, lint-commits, test-unit, get-version, build]
    permissions:
      contents: write
      pull-requests: write
    uses: jrposada/github-actions/.github/workflows/semantic-release.yml@v2
    with:
      artifact-name: lib
      artifact-path: ./jrposada-ts-util-${{ needs.get-version.outputs.version }}.tgz
