name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-eslint:
    name: 'Lint: ESLint'
    uses: jrposada/github-actions/.github/workflows/npm-script.yml@v1
    secrets: inherit
    with:
      script: 'lint:eslint'

  lint-format:
    name: 'Lint: Format'
    uses: jrposada/github-actions/.github/workflows/npm-script.yml@v1
    secrets: inherit
    with:
      script: 'lint:format'

  lint-types:
    name: 'Lint: Types'
    uses: jrposada/github-actions/.github/workflows/npm-script.yml@v1
    secrets: inherit
    with:
      script: 'lint:types'

  test-unit:
    name: 'Test: Unit'
    uses: jrposada/github-actions/.github/workflows/npm-script.yml@v1
    with:
      script: 'test:coverage'
